name: yx_tool
description: Contains a series of commonly used toolkits, including encryption and decryption modules, id generation, date processing, extension methods of basic classes...
version: 0.1.2
homepage: https://github.com/yixiaco/yx_tool

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  pointycastle: ^3.6.0 #摘要加密、非对称加密、对称加密
  convert: ^3.1.0
#  path: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  pedantic: ^1.11.1 #Google 内部使用的 Dart 分析器设置和最佳实践